### ISSUE TITLE
UI Improvement: Make Lenders Market Screen responsive

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#1]
<img width="375" alt="Screenshot 2024-10-18 at 05 41 48" src="https://github.com/user-attachments/assets/9c6e4cb1-c191-4a55-b102-de89d986ebb7">

This is an image of what the lend market screen looks like.

Your task if you choose to accept it, is to make this page Screen responsive across different media.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi

**Comment by Dprof-in-tech** [comment]
Hey guys
Please these issues would be open for the ODHack 9 edition so please  apply to solve them by the start of the ODHACK. Thank you.

**Comment by wheval** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hello @Dprof-in-tech, I'm Wheval, a frontend developer with 3 years experience building responsive and user-friendly interfaces with React, typescript and css. I would really love to contribute to Peer Protocol. With my experience i can fix this make this responsive ASAP.

### How I plan on tackling this issue
I would inspect the current design and align the contents of the page layout to repond to different media queries depending on screen sizes. And also ensure fluid width of the layout element and font sizes according to the existing UI design of the page.

ETA is 1 day.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hello! I'm a front-end and a blockchain developer. I will love to work on and solve this issue. Assign please

### How I plan on tackling this issue

- I will analyze the provided image and the existing code to understand the layout and identify areas that need adjustments for responsiveness.
- In my TypeScript components, I will adjust styles. Utilize media queries to modify layout and element styles based on screen sizes. I will focus on widths, margins, and padding for each breakpoint.
- Using styled-components or another CSS-in-JS library, I will refactor the component layouts with Flexbox or Grid to ensure they are adaptable.
- I will use tools like Chrome DevTools or device simulators to inspect the responsiveness of my components on various screen sizes. I will fix any component overlaps or alignment issues.
Thanks

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
**hello @Dprof-in-tech i'm a frontend dev and blockchain dev and i would like to work on this issue :)**


### How I plan on tackling this issue
i would make sure to make the screen responsive and pixel perfect on all devices

please kindly assign :)

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I wil make the lenders market screen responsive

**Comment by web3normad** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a result-driven  Web3 frontend developer with good experience in creating responsive, functional, and visually appealing and user friendly user interfaces. I have worked on various projects within the web2 and web3 space with some of my projects being in the Aya builders incubation program, I am currently the team lead of my team involved in  Web3 integrations, and blockchain interactions, which requires a strong focus on user experience across devices. My background in working with React, and CSS frameworks such as SCSS and TailwindCSS gives me the ability to quickly adapt and enhance designs for responsiveness, ensuring smooth user interactions on both mobile and desktop platforms.

### How I plan on tackling this issue
To approach the problem, I would start by, analyzing the existing layout of the lenders market market screen and pick the areas that need responsiveness. I will Implement a mobile-first approach using TailwindCSS,  to make sure that the design scales well for all screen sizes, especially mobile. I will use Flexbox  to create a smooth layout that adjusts dynamically to different screen sizes. I will ensure that the text, buttons, labels, icons and any other item on the page are set on smaller screens by adjusting their sizes accordingly. I will test the design across multiple devices and browsers to ensure consistency in user experience, and lastly I would optimize the page load time by ensuring the images, fonts, and other assets are scaled properly for mobile devices to ensure faster rendering. These are the steps I would follow to approach the problem

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I will make the screen responsive.
ETA: 24hrs

**Comment by chibokaxavier** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi, I’m Chiboka Xavier, a full-stack developer with over 4 years of experience building applications that not only work well but feels great to use. I’m passionate about turning creative UI/UX designs into real, responsive user interfaces with tools like Next.js, React, and Tailwind CSS. On the backend, I use Express and MongoDB to make sure everything runs smoothly behind the scenes. I love exploring new technologies and finding ways to create seamless, enjoyable experiences for users, blending both the frontend and backend to bring ideas to life.

### How I plan on tackling this issue
1.To make the layout responsive, I’ll break the page into three key parts: the header, the table, and the action buttons. I’ll use Tailwind’s utility classes to make sure each section adjusts smoothly depending on the screen size.

2.For the header, I’ll utilize the  flex property to line up the back button, page title, and Starknet icon. This way, they’ll display properly on both large and small screens. I’ll also make sure there's enough spacing between them.

3.For the table, I’ll wrap it in a container with the overflow-x-auto property, so users can scroll horizontally on smaller screens if needed. I’ll make sure the table stretches across the full width and add some padding to keep it easy to read.

Lastly, for the action buttons and pagination, I’ll stack them vertically on smaller screens and switch to a horizontal layout on larger ones using the flex-col sm:flex-row property. I’ll use the justify-between property to evenly space them out, ensuring everything looks well-balanced and user-friendly, no matter what device you're on.

**Comment by Mystic-Nayy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a frontend/web3 developer

### How I plan on tackling this issue
I will Implement a flexible layout using CSS Flexbox or Grid to adjust element positioning for different screen sizes. Add media queries to modify styles, such as font sizes and margins, for mobile, tablet, and desktop views. Test the page across various devices to ensure all components are displayed correctly and are user-friendly.

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
**UI Improvement: Make Lenders Market Screen responsive**

Hello peer on strk team,

I am Joel Vargas, and I'm a member of Dojo Coding. I also come from OnlyDust.

I would like to request the assignment of this issue. Below is my proposed approach for implementing this issue:

### How I plan on tackling this issue
### Proposal for Making the Lend Market Screen Responsive

#### Objective
The goal of this task is to ensure that the Lend Market screen is responsive across various media devices, providing an optimal user experience on desktops, tablets, and mobile phones. This will enhance usability and accessibility for all users, regardless of the device they are using.

#### Design Considerations
1. **Fluid Layout:**
   - Utilize a fluid grid system that adjusts based on the screen size. Use Tailwind’s responsive utility classes to create a layout that adapts to different screen widths.
   - Ensure that the overall structure remains intact while allowing elements to resize and reposition gracefully.

2. **Breakpoints:**
   - Leverage Tailwind’s default breakpoints to control layout and styling across different device sizes:
     - **sm (640px):** For small devices (phones)
     - **md (768px):** For medium devices (tablets)
     - **lg (1024px):** For large devices (desktops)
     - **xl (1280px):** For extra-large devices (large desktops)

3. **Adjustable Content:**
   - Ensure that text, images, and buttons are flexible and scale appropriately. Use Tailwind’s typography utilities to adjust font sizes and line heights for readability on smaller screens.
   - Consider using Tailwind’s padding and margin utilities to create space between elements, ensuring that they do not become cramped on smaller displays.

4. **Navigation:**
   - Implement a mobile-friendly navigation menu. This could involve collapsing the navigation into a hamburger menu on smaller screens, making it easy for users to access different sections without taking up too much space.
   - Ensure that the navigation remains intuitive and accessible regardless of the device being used.

5. **Cards and Tables:**
   - If the Lend Market screen includes cards or tables to display information, ensure they are responsive. Cards should stack vertically on smaller screens and display side-by-side on larger screens.
   - Use Tailwind’s grid or flex utilities to manage the layout of these components, ensuring they remain user-friendly and easy to interact with.

6. **Images and Media:**
   - Ensure that images are responsive by using utility classes that allow them to scale based on the parent container's width. This prevents overflow and maintains visual appeal across devices.
   - Consider using aspect ratio utilities to maintain the integrity of images when resizing.

7. **Testing Across Devices:**
   - Conduct thorough testing on various devices (smartphones, tablets, desktops) to ensure that the design holds up in real-world scenarios.
   - Utilize browser developer tools to simulate different device sizes and make adjustments as necessary based on observations.

#### Implementation Steps
1. Review the existing Lend Market screen layout and identify areas that require adjustments for responsiveness.
2. Implement Tailwind CSS responsive utility classes for layout, typography, and spacing.
3. Adjust navigation for mobile usability.
4. Test the screen across multiple devices and screen sizes to ensure a seamless experience.

#### Definition of Done
- The Lend Market screen is fully responsive across different media devices.
- The design maintains usability and aesthetic appeal on all screen sizes.
- All changes are documented, and the code is committed to the repository for review.

#### Next Steps
- Collaborate with team members to gather feedback on the responsive design.
- Make necessary adjustments based on testing outcomes and user feedback.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Make the lend market screen responsive and test to ensure it works as expected

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
There is nothing much to comment on. I will look into the CSS of the market screen, work on it and make it responsive
ETA - few hours once assigned

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To improve the user experience on the Lenders Market screen, I will focus on making the page responsive across various devices and screen sizes. This involves evaluating the current design and identifying elements that need to be adjusted for optimal display on different media.

I will utilize responsive design techniques, including flexible layouts, media queries, and scalable UI components, to ensure that all content remains accessible and visually appealing on mobile phones, tablets, and desktop screens. After implementing these changes, I will conduct thorough testing on multiple devices to ensure a consistent and user-friendly experience on the Lenders Market screen.

**Comment by stephanniegb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I’m a frontend engineer with  experience in building responsive, interactive UIs. I’ve worked on implementing pixel-perfect designs, and optimizing performance across various projects.

### How I plan on tackling this issue
I will use CSS media queries to ensure the page is responsive across various screen sizes.
