### ISSUE TITLE
SMART CONTRACT: Write Tests for Deposit Function.

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#11]
The Deposit function can be found here:
[https://github.com/Dprof-in-tech/peer-on-strk/blob/main/contracts/src/peer_protocol.cairo](url)

Write tests for it .

**Comment by Dprof-in-tech** [comment]
Could I grab this task?

**Comment by ptisserand** [comment]
Can I start working on this?

I will create several test cases with starknet foundry to check normal flow and expected failures.

**Comment by TEMHITHORPHE** [comment]
This appears to be a pretty straightforward Cairo testing, and a good first issue, I would be happy to take this on as hopefully my first Cairo contribution, i already have Cairo knowledge as a graduate of Basecamp ix, and i believe i can have a PR ready before end of day, I already looked through the concerned source file here:  https://github.com/Dprof-in-tech/peer-on-strk/blob/main/contracts/src/peer_protocol.cairo, and would like to start immediately, thank you.
