### ISSUE TITLE
FE: Integrate smart contract with frontend

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#21]
the deposit and withdraw functions have been built with the smart contract deployed on sepolia ETH. Integrate the frontend with the smart contract so that we can deposit and withdraw tokens into and out of the smart contract.

**Comment by Jemiiah** [comment]
@Dprof-in-tech can I work on this issue

**Comment by Iwueseiter** [comment]
Hi @Dprof-in-tech can I work on this?

**Comment by PoulavBhowmick03** [comment]
I am Poulav Bhowmick, a fullstack blockchain engineer, a Starknet Wolf and Superteam grants recipient. 

I have a good experience in integrating StarkNet smart contracts with frontend in next.js or react.js. I can complete this task in a day
