### ISSUE TITLE
CONTRACTS: Build a function to retrieve a user's assets in the smart contracts

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#24]
this function should take a caller address as the currently connected user, pull up their total assets lent, total assets borrowed, interest earned and available balnce which should default to total of depsits when nothing has been borrowed.

All these data would be stored fully onchain for now.

write the function and write the tests for it.

**Comment by Jemiiah** [comment]
@Dprof-in-tech can I work on it

**Comment by casweeney** [comment]
I can take up this issue.

Giving that I already understand how this code works, I will create a function that retrieves user's assets in the smart contract.

## ETA: 4hours

**Comment by wheval** [comment]
I’d like to resolve this. I would enusre all tests pass correctly.
ETA is 1 day

**Comment by Josh-121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged

software engineering background, backend & smart contract dev looking to make first contribution on this project

How I plan on tackling this issue
implement the required function
work on feedback & recommendation ensuring contact. Can deliver within a day
