### ISSUE TITLE
CONTRACTS:  Build function to retrieve a user's assets deposited into the protocol

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#25]
This function should retrieve the assets a user holds in the protocol and prep it to be displayed in the assets overview tab of the portfolio page.

write the functions and the tests.

**Comment by Kaminar-i** [comment]
Can I tackle this one?

**Comment by wheval** [comment]
Can i work on this? @Dprof-in-tech

**Comment by Josh-121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged

software engineering background, backend & smart contract dev looking to make first contribution on this project

How I plan on tackling this issue
implement the required function
work on feedback & recommendation ensuring contact. Can deliver within a day

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with strong experience contributing to other projects, I would love to work on this.

**Comment by ShantelPeters** [comment]
May I handle this issue?

I’ll implement a `getUserAssets` function to retrieve the assets a user holds in the protocol, organizing the data for display in the assets overview tab on the portfolio page. This will include asset type, quantity, and value. I’ll also write unit tests to cover various scenarios, including users with no assets and those with diverse asset types, to ensure the function returns accurate and display-ready data.

**Comment by kfastov** [comment]
Is it okay if I tackle this?
I have an experience in Cairo, both contributing in open source projects and developing my own.
