### ISSUE TITLE
CONTRACTS: Build a smart contract to retrieve a users transaction history into the protocol

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#26]
This smart contract function should retrieve the user's transaction history in and out of the peer protocol smart contract and prep it to be displayed in the transaction history tab on the portfolio page.

write the function and its tests.

**Comment by martinvibes** [comment]
Can I work on this issue?

**Comment by Josh-121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged

software engineering background, backend & smart contract dev looking to make first contribution on this project

How I plan on tackling this issue
implement the required function
work on feedback & recommendation ensuring contact. Can deliver within a day

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with strong experience contributing to other projects, I would love to work on this.

**Comment by ShantelPeters** [comment]
I’d like to help with this.
Firstly i will create a `getTransactionHistory` function to retrieve and format a user's transaction data for display, ensuring each entry includes transaction details. 
Then  i will write unit tests covering different transaction scenarios to verify data accuracy and format.

**Comment by omsant02** [comment]
i would like to work on this issue

i am planning to solve this issue by
Implementing the retrieve_transaction_history function that takes the user's address as an input parameter, iterates through their deposit and withdrawal records in the contract's storage, and returns a vector containing the token address, amount, and timestamp for each transaction.

**Comment by ShantelPeters** [comment]
Hi @Dprof-in-tech 
Is this still open for contribution ?

**Comment by Dprof-in-tech** [comment]
someone is still working on it, which is why i reopened it but if it becomes free, i'd let you know

**Comment by omsant02** [comment]
@Dprof-in-tech 

i have raised the final pr,
please review it
