### ISSUE TITLE
FE: Integrate the get_user_deposits function

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#30]
This function retrieves the assets a user holds within the platform and displays it in the assets overview tab on the profile page.

Also implement a pagination on the tab so that it only contains 10 items per page.
I would provide the contract address for the smart contract to be used. Please specify your Expected time of delivery and do not apply to this issue if you would not have a draft PR open by end of day.

Thank you.

**Comment by Benjtalkshow** [comment]
Hello, @Dprof-in-tech . This is my first time contributing to this project. I’m a frontend developer with 4 years of experience, skilled in Next.js and TypeScript. I’ll create a solid PR within 10 hours and ensuring the implementation is fully responsive and adaptive to various screen sizes. Thank you

**Comment by Michaelkingsdev** [comment]
Can I contribute to this one? This will be my first time contributing to this project. ETA 8hrs.

**Comment by mimisavage** [comment]
Could I take a shot at this?

**Comment by ShantelPeters** [comment]
Hello @Dprof-in-tech 
Please can I be assigned to this issue?
This would be my first time contributing to this ecosystem.

**Comment by wheval** [comment]
Hello @Dprof-in-tech,  I'm a frontend developer with experience building web applications and user-friendly interfaces with React and typescript. I would ensure to retrieve the user's assets and display it properly using the correct types  and also implement the pagination to contain only 10 items, i would also test it. I would definitely create a draft PR before the end of the day.
ETA is 1 day.
