### ISSUE TITLE
FE: Integrate the get_user_assets function 

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#31]
This function retrieves the assets a user holds within the platform and displays it in the cards available on the profile page.

its retrieveal includes :
total lent
total borrowed
Interest earned
available balance

I would provide the contract address for the smart contract to be used. Please specify your Expected time of delivery and do not apply to this issue if you would not have a draft PR open by end of day.

Thank you.

**Comment by FemiOje** [comment]
Hi. I'm a frontend web developer with 3 years experience and I also have experience building smart contracts with cairo. 

How I would approach this:
1. Call the get_user_assets() endpoint from the contract address provided, providing the user's address as the 'user' argument. 
2. Create a dropown menu of the user's tokens from each token_address provided in the Array<UserAssets>(from the deposit/withdraw section in the frontend I assume these might be only ETH and STRK).
3. When the user selects a token from the dropdown menu:
    - display the token image and token name
    - display the total lent, total borrowed, interest earned, and available balance for the selected token in the cards below/provided.
4. Provide placeholder/error text in case error occurs in fetching data.

Expected time of delivery: 12 hours.
Draft PR/submission will be provided by end of day.

**Comment by mimisavage** [comment]
Can I be assigned to this?

**Comment by Benjtalkshow** [comment]
Hello, @Dprof-in-tech . This is my first time contributing to this project. I’m a frontend developer with 4 years of experience, skilled in Next.js and TypeScript. I’ll create a solid PR within 10 hours and ensuring the implementation is fully responsive and adaptive to various screen sizes. Thank you

**Comment by Michaelkingsdev** [comment]
I’d love to work on this task. ETA 10hrs

**Comment by ShantelPeters** [comment]
Please can I work on this @Dprof-in-tech

**Comment by TEMHITHORPHE** [comment]
so let's see:
I'll make a call to the smart contract function, returns the assets (supported token) of the user, then create Cards on the frontend that correspond to the supported token which details the user's assets.
ETA: I will have a draft PR before end of day as requested.

**Comment by wheval** [comment]
Hello @Dprof-in-tech,  I'm a frontend developer with experience building web applications and user-friendly interfaces with React and typescript.
I would ensure to retrieve and display all the data listed properly using the correct types.
I would also test it to ensure it works.
I would create a draft PR before the end of the day.
ETA is 1 day.

**Comment by Aditya-040** [comment]
Can I contribute to this one?

**Comment by Aditya-040** [comment]
I'd like to take this issue. I will do it in 1 day.
