### ISSUE TITLE
INTEGRATE WAITLIST TO GOOGLE SHEETS

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#4]
Integrate the peer protocol waitlist which can be found at https://peer-on-strk.vercel.app/Waitlist to a google sheet to store the data on submission.

New Details on this Issue:
The framework in use for this project is Nextjs so your solutions should be tailored towards levergaing what Nextjs can do for the form submissions and integration of google sheets.

if you have any questions, do not hesitate to ping me or ask a question in our telegram group.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will Integrate the peer protocol waitlist to store data on submission

**Comment by KodeSage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I'm James Harrison, A Seasoned Software Engineer well experienced and crafted in both the web2 and web3 space 

### How I plan on tackling this issue
I would export the the form submission to excel sheets using some React Libraries

**Comment by Samuel1-ona** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

**My background and how it can be leveraged**
Hello , i am samuel , i am a blockchain developer and a security researcher 

**How I plan on tackling this issue**

1. I will inspect the waitlist form to see if it is structured and clean 
2. Go to Google Sheets and create a new spreadsheet to store the submitted data and Name the 
columns according to the fields in the waitlist that is according to the individual and business feilds.
3. I will write a script that will store the waitlist 


This is my first application to onlydust, if i am assigned i will execute very fast.

Thank you.

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I will integrate  the waitlist to a google sheet

**Comment by juandiegocv27** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I’m a software engineer with experience in both front-end and blockchain development, and I've worked with several technologies like Rust, JavaScript, and Typescript. I’ve contributed to open-source projects and participated in Web3 initiatives, particularly those within the Starknet ecosystem, so I’m familiar with decentralized platforms and blockchain integrations. I’ve also worked on projects where I needed to capture data from forms and integrate it into external systems, which is similar to what’s needed for this task.

### How I plan on tackling this issue
I would start by reviewing the current waitlist form at the provided URL to understand how it’s structured and how the data is collected. Then, I’d create a Google Sheet with columns matching the form fields. I would set up the Google Sheets API and create a service account to allow data submission from the form. Once that’s done, I’d integrate the Google Sheets API with the existing form using TypeScript, ensuring that the form data is sent directly to the Google Sheet on submission. Finally, I’d test the entire process by submitting entries to ensure everything works correctly, and debug any issues that arise along the way.

**Comment by Jayse007** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I would like to take this job to be delivered by 1st of November. 
I have experience working with files in Python. I can manipulate googlesheets with the aid of a python module called gsheet. So updating the data received will be no problem with python.

### How I plan on tackling this issue
I would make use of gsheet module in python to add the entries from the frontend form into the specified googlesheet. Once the data is submitted by the user and my python script receives it, it will be arranged according to your specifications - the columns, capitaliation and so on.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To integrate the peer protocol waitlist from the provided URL into Google Sheets, I will set up a system that captures user submissions from the waitlist and automatically stores the data in a designated Google Sheet. This will involve creating a form that collects necessary information from users and connecting it to the Google Sheets API to ensure seamless data transfer.

Once the integration is complete, all submissions from the waitlist will populate the Google Sheet in real-time, allowing for easy tracking and management of the waitlist data. If there are any questions or if clarification is needed during the process, I will reach out directly for assistance.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by emarc99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I have a strong background (1 year) in blockchain development, with expertise in writing Solidity, and fundamental knowledge of Cairo, and zero-knowledge proofs (zk). I have built dApps on Ethereum (and Scroll) using token standards; UniSwapv2 clone, Multi wallet, Gated NFT Event Management system, Crowdfunding. I also do FE/wallet integration using Reown, web3js and ethersjs. As well as subgraph for efficient indexing.

This issue will enable me to contribute to an open-source project for the first time, learn and build.

### How I plan on tackling this issue
1. Create and set up a new blank Spreadsheet
2. Access Appscript from the Spreadsheet, in a new web-based editor
3. Add a script and deploy the app
4. Copy and save deployment ID and Web App URL
5. Set up a Trigger for Valid Submission from Waitlist website (https://peer-on-strk.vercel.app/Waitlist)
6. Implement into Waitlist form, pass deployed app ID to the base URL
Issue solved.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
would love to work on this

**Comment by blessingbytes** [comment]
I'd love to work on this!

**Comment by ikezuby2012** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

My background and how it can be leveraged
Hi, I’m zuby, a fullstack and blockchain developer. i have a strong background in web development especially building API with expertise in writing nodejs and asp.net, This is my first time contributing to this repository, and I'm excited about the opportunity to collaborate.

How I plan on tackling this issue

Build an API: i will use a framework like Node.js or .NET to build a simple REST API that accept the required credentials and placeholders (e.g., customer data) in the JSON payload.
Google Sheets and Drive Setup: then Use the Google Sheets API to create a new Google Sheet in the assigned Google Drive and leverage the Drive API to manage file creation and permissions for access.
App Script for CSV Creation: Write a Google Apps Script to automate the creation of a CSV file from the Google Sheet. This script will Pull data from the sheet, Replace placeholders in the template, Convert the final data into CSV format, After placeholders are replaced, the script will Generate the CSV file and save it in the Google Drive folder or provide a downloadable link for the API response.

ETA: Two days

**Comment by jaiminRaiyani** [comment]
May I take this issue on?

**Comment by Jemiiah** [comment]
@Ugo-X and @Dprof-in-tech can I take this up ?

**Comment by DotworldX** [comment]
May I take this issue on?

**Comment by reetbatra** [comment]
I'd love to work on this!

**Comment by shubha-me** [comment]
Could I be assigned to this?

**Comment by kfastov** [comment]
I'm a Full Stack Web3 Developer and currently developing my personal project using Next.js, so I already have experience with it. I would quickly learn the Google API and implement the hooks that will update the desired worksheet based on new submissions.
May I be assigned to this?

**Comment by neonflux-io** [comment]
I'm a Full Stack Web3 Developer and currently developing my personal project using Next.js, so I already have experience with it. I would quickly learn the Google API and implement the hooks that will update the desired worksheet based on new submissions.
May I be assigned to this?
