### ISSUE TITLE
Smart Contract: Write a cairo smart contract to support token deposits .

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#5]
We would love a smart contract that would support token deposits into the protocol from your wallet, first on sepolia eth.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.


### How I plan on tackling this issue
I'll implement this token deposit functionality for the protocol. Here is the detailed implementation

1. i will create a cairo smart contract with the following core features:
   - ERC20 token deposit functionality
   - Deposit balance tracking per user/token
   - Token support whitelist system
   - Event emission for deposits

2. Details
- Include comprehensive deposit validation checks
- Add admin functions for token management
- Implement proper access controls
- Add thorough testing suite

3. Tests
1. Unit tests for all core functions
2. Integration tests with mock ERC20 tokens
3. Testing on Sepolia testnet

# ETA - 2 days
I have an extensive experience in building robust frontends for applications and startups. I can get this done in few hours by working on the CSS of the borrow market

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I'm Joseph a blockchain developer with over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
Begin by studying the codebase to ensure design consistency, then proceed to work on the task.

1. Study current codebase design
2. Write token contract wrt to design standards
4. Add tests to make sure the implementation works and no adverse effects
5. And lastly optimize

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi, I am a skilled Cairo dev with lots of experience contributing to amazing projects, my profile is a witness to that statement.

### How I plan on tackling this issue
I'll create a 'Vault' contract which will be holding the deposited tokens and it will support the necessary interface required to enable deposit of tokens. I'll ensure necessary events are emitted and the contract has a full test coverage.

**Comment by casweeney** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.


### How I plan on tackling this issue
I will approach this issue in the following way:
1. Create a contract interface for the smart contract I will be writing, add the `deposit` function signature to the interface.

2. Create an `IERC20` interface which will be used to interact with `ERC20` tokens using the `IERC20Dispatcher`.
3. Implement the `deposit` function that allows users to deposit ERC20 tokens.

4. Create mock ERC20 tokens that will be used for testing purposes.

## ETA: 1 day

With my experience in writing and testing Cairo smart contracts, I will deliver this task in a day.

**Comment by kfastov** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I'm a Full Stack Web3 Developer with experience in Rust and Cairo and participated in ODHacks since 2.0, working as both a contributor and maintainer.
I am also writing Cairo in my own projects and keep in touch with the latest Cairo 2 features like iterators

### How I plan on tackling this issue
1. I would quickly research the project to learn the current flow of contract interaction.
2. implement a contract with a deposit method, token whitelist, deposit events, ownership, upgradable, pausable (for any unforeseen cases) and so on
3. implement unit tests for all methods and integration tests using mock contracts
4. deploy contracts on testnet and verify
5. document new contracts
ETA: 2 days

**Comment by Pvsaint** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I'm Victor Peter, a front-end and smart contract developer

### How I plan on tackling this issue
I'll define the token deposit contract, define the get balance function, define the set balance function

**Comment by Ugo-X** [comment]
assigned @casweeney goodluck
link to our group:
https://t.me/+p7vbt9n01blhZDY0
