### ISSUE TITLE
Change All SVG Icon imports to use Icons from lucide-react icon library where available

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#7]
Find and replace all svg icon image imports with their standard counterpart icons from the lucide-react icon library.

**Comment by Mystic-Nayy** [comment]
@Dprof-in-tech can I work on this?

When I am assign I will Install `lucide-react` and replace all SVG icon imports with the corresponding icons from the library. Update your imports to use `import { IconName } from 'lucide-react'` and replace SVG elements with `<IconName />` components.

**Comment by martinvibes** [comment]
**hello @Dprof-in-tech i'm a frontend dev and blockchain dev and i would like to work on this issue :)**
### Here’s a summarized version of the process in steps:

- Install lucide-react:
`npm install lucide-react`

- Identify SVG Icons: Find all SVG icon imports in the codebase.

- Replace with Lucide Icons: Replace SVG imports with their lucide-react counterparts.

- Update JSX: Swap the old SVG components with Lucide icon components in the JSX.

- Adjust Styling: Ensure the new icons match the size, color, and style of the original SVGs.

- Test the Application: Verify that all icons render correctly after the changes.

Please kindly assign :)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hello! I'm a front-end and a blockchain developer. I will love to work on this please

### How I plan on tackling this issue
Steps I intend to use so as to achieve a solution:
- I will start by installing the icon library in the project.
- I will search the codebase for direct SVG imports or usage.
- I will replace each SVG import with the corresponding Lucide icon from `lucide-react`. 
- I will update the JSX/TSX code to render Lucide icons as components. 
- I will then customize the size and color props as needed.
- I will ensure that all replaced icons are displayed correctly in the UI. Checking different components and pages to verify that there are no missing or incorrectly rendered icons.
Thanks allot

**Comment by ryzen-xp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a Full stack Blockchain developer with expertise in Cairo, Solidity, Rust, and Web2 technology . I’ve contributed to open-source projects such as Worldcoin-Bridge-Linea and ArkProjectNFTs Bridge and more .

### How I plan on tackling this issue
I’d locate all SVG icon imports, replace them with the corresponding icons from the lucide-react library, and then test the application to ensure the icons work correctly.
Please assign me sir/mam

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will ensure the requirement is met by changing the svg to lucide-react icons

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi, I'm Collins a frontend and blockchain developer, and an active contributor on OnlyDust. You can check out my profile here: https://app.onlydust.com/u/0xdevcollins. This is my first time contributing to this repository, and I’m excited about the opportunity to contribute. Looking forward to collaborating!

### How I plan on tackling this issue
I will import lucid-react icon library, scan through the code to and change svg to lucite-react icons

**Comment by sanieni6** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
hi there, I am Luis a front-end developer with 2 years of experience, I will be glad to contribute to this project my man.

### How I plan on tackling this issue
1. Install lucide-react
2. Replace all the SVG icon with the icons from the library

**Comment by chibokaxavier** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi, I’m Chiboka Xavier, a full-stack developer with over 4 years of experience building applications that not only work well but feels great to use. I’m passionate about turning creative UI/UX designs into real, responsive user interfaces with tools like Next.js, React, and Tailwind CSS. On the backend, I use Express and MongoDB to make sure everything runs smoothly behind the scenes. I love exploring new technologies and finding ways to create seamless, enjoyable experiences for users, blending both the frontend and backend to bring ideas to life.

### How I plan on tackling this issue
To replace all SVG icon imports with the standard counterparts from the lucide-react library , I’ll start by searching for all the SVG imports in various components. Then, I'll find the matching icons in the lucide-react library. After doing that, I'll update the imports to look like "import { IconName } from 'lucide-react';. I’ll also change how I use these icons in my JSX by swapping out "<IconName className="h-6 w-6" />" for the new icons, making sure that  everything still looks good. Finally, I’ll run the app to make sure everything works without any missing imports or errors.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Go through all svgs and find exact match on the lucide-react icon library and replace them

**Comment by wheval** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hello @Dprof-in-tech,  I'm Wheval, a frontend developer with experience building responsive and user-friendly interfaces with React, typescript and css. This would be my first contribution to Peer protocol. I would really love to contribute. Thanks.

### How I plan on tackling this issue
To replace all the svg icons, I would follow these simple steps i outlined

1. **Install Lucide Icons**  
   First i would, check if the `lucide-react` is in the node_modules else i would install it by running the following command:  
   `npm install lucide-react`

2. **Identify SVG Icons**  
   Next, I would use the VSCode search functionality to find all SVG icon imports and `<img>` tags that use SVGs in the codebase.

3. **Replace with Lucide Icons**  
   I would replace the SVG imports with their corresponding `lucide-react` icons that match their partiular use cases.

4. **Update JSX**  
  I would change the old SVG components to the Lucide icon components in the JSX.

5. **Adjust Styling**  
   I would also ensure the new icons match the size, color, and style of the original SVGs.

6. **Render the Application**  
   Finally, i would verify that all icons render correctly after the changes.

ETA is 1 day.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will replace all SVG icon imports in the project with icons from the lucide-react icon library wherever applicable. This will involve reviewing the existing SVG icon usages and identifying their standard counterparts in the lucide-react library. After updating the imports, I will ensure that the new icons are correctly integrated and visually consistent with the overall design of the application. This change will enhance maintainability and leverage the benefits of a consistent icon library.

**Comment by stephanniegb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hello, I am frontend  dev and i will like to work on this

### How I plan on tackling this issue
- i will find and replace  all icon images with SVG alternatives

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I am a frontend develop with experience using material-ui lucide-react library and other frontend technologies

### How I plan on tackling this issue
To replace all SVG icon imports with standard icons from the lucide-react icon library, follow these steps:

Install the Lucide-react library:
Run npm install lucide-react or yarn add lucide-react to add the library to your project.

Identify SVG Imports:
Locate all instances where SVG icons are imported. Typically, these will be direct imports like import MyIcon from './icons/myIcon.svg';.

Replace with Lucide-react icons:
For each identified import, find the corresponding Lucide-react icon. For example, if you're using an SVG for a home icon, replace it with Lucide's Home icon by importing it as follows:
import { Home } from 'lucide-react';

Update JSX:
Replace the JSX where the SVG was used with the Lucide-react component.
