### ISSUE TITLE
DESIGN: Gamified Quest Design

### ISSUE THREAD

**Issue by Dprof-in-tech** [Dprof-in-tech/peer-on-strk#8]
Suggest and design a quest approach to using peer protocol. would require indepth discussion with whoever is assigned to iron out what is what.

**Comment by od-hunter** [comment]
Hi @Dprof-in-tech , please I’d love to be given the opportunity to come up with the design for this. Please ser. I’m ready to work.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
Hi @Dprof-in-tech , please I’d love to be given the opportunity to come up with the design for this.

I have great experience in ui/ux design. Please ser, I’m ready to work.

**Comment by Osatuyi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/peer-protocol).

### My background and how it can be leveraged
I'm a designer with 2years experience in the field. I'll like to work on this project. I've been designing web3 gamified products for a while and I deliver a good job.

### How I plan on tackling this issue
I'll work with the team to come up with a design system if there isn't one already. I'll observe the trend used for web3 quests and use that to come up with concepts for a neat ui for the quest design

**Comment by Ugo-X** [comment]
assigned @od-hunter  good luck

link to our group:
https://t.me/+p7vbt9n01blhZDY0
